import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";

/**
 * Root Layout (App Router)
 * -----------------------
 * In Next.js App Router (`src/app`):
 * - `layout.tsx` wraps every page.
 * - This file is a Server Component by default (no `"use client"`).
 * - Great place for global HTML structure, fonts, global CSS, analytics, etc.
 */

/**
 * Fonts (next/font)
 * -----------------
 * `next/font` loads fonts in an optimized way (no layout shift, automatic subsets).
 * The `variable` field lets us reference the font via CSS variables.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Metadata
 * --------
 * This controls the document title/description (used for SEO + browser tab title).
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* `antialiased` and font variables apply to the whole app */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
